#!/bin/bash
cur_dir=`pwd`
dir=${cur_dir##*/}
del_files=("build" "dist" "order_manage.egg-info")

if [ $dir == "tools" ];
then
	cd ..
fi

for file in ${del_files[@]}
do
	if [ -e $file ];
	then
		rm -rf $file
	fi
done

echo "Del files generated by setup over!"
